credentials:
  usernames:
    dkurzyk:
      email: dariusz.kurzyk@locationengine.com
      name: Dariusz Kurzyk
      password: $2b$12$4XhrLBF3ePKAMziGLZvRz.QDLd/Qcvz/9ekhDlAeJfVesHEHu3aIq # To be replaced with hashed password
    le:
      email: le@locationengine.com
      name: Location Engine
      password: $2b$12$hTgNth8O4oMsTvhvLTZaMu2RDzQarzSxAh7pqd/lTUwDvBNnEw8Eu # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - dariusz.kurzyk@locationengine.com
